//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/rollingBallRouting/RollingBallRoutingPacket.msg.
//

#ifndef _ROLLINGBALLROUTINGPACKET_M_H_
#define _ROLLINGBALLROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
#include "GeoMathHelper.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/rollingBallRouting/RollingBallRoutingPacket.msg:11</tt> by nedtool.
 * <pre>
 * enum RollingBallForwardingMode
 * {
 * 
 *     GREEDY_ROUTING = 0;
 *     ROLLINGBALL_ROUTING = 1;
 * }
 * </pre>
 */
enum RollingBallForwardingMode {
    GREEDY_ROUTING = 0,
    ROLLINGBALL_ROUTING = 1
};

/**
 * Enum generated from <tt>src/node/communication/routing/rollingBallRouting/RollingBallRoutingPacket.msg:16</tt> by nedtool.
 * <pre>
 * enum RollingBallPacketDef
 * {
 * 
 *     ROLLINGBALL_DATA_PACKET = 0;       // data packet
 * }
 * </pre>
 */
enum RollingBallPacketDef {
    ROLLINGBALL_DATA_PACKET = 0
};

/**
 * Class generated from <tt>src/node/communication/routing/rollingBallRouting/RollingBallRoutingPacket.msg:20</tt> by nedtool.
 * <pre>
 * packet RollingBallPacket extends RoutingPacket
 * {
 *     int packetId;
 *     int RollingBallPacketKind @enum(RollingBallPacketDef);
 *     int routingMode @enum(RollingBallForwardingMode);
 *     Point destLocation;
 *     Point stuckLocation;
 *     Point ballCenter;
 *     Point previousLocation;
 * }
 * </pre>
 */
class RollingBallPacket : public ::RoutingPacket
{
  protected:
    int packetId_var;
    int RollingBallPacketKind_var;
    int routingMode_var;
    Point destLocation_var;
    Point stuckLocation_var;
    Point ballCenter_var;
    Point previousLocation_var;

  private:
    void copy(const RollingBallPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RollingBallPacket&);

  public:
    RollingBallPacket(const char *name=NULL, int kind=0);
    RollingBallPacket(const RollingBallPacket& other);
    virtual ~RollingBallPacket();
    RollingBallPacket& operator=(const RollingBallPacket& other);
    virtual RollingBallPacket *dup() const {return new RollingBallPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getRollingBallPacketKind() const;
    virtual void setRollingBallPacketKind(int RollingBallPacketKind);
    virtual int getRoutingMode() const;
    virtual void setRoutingMode(int routingMode);
    virtual Point& getDestLocation();
    virtual const Point& getDestLocation() const {return const_cast<RollingBallPacket*>(this)->getDestLocation();}
    virtual void setDestLocation(const Point& destLocation);
    virtual Point& getStuckLocation();
    virtual const Point& getStuckLocation() const {return const_cast<RollingBallPacket*>(this)->getStuckLocation();}
    virtual void setStuckLocation(const Point& stuckLocation);
    virtual Point& getBallCenter();
    virtual const Point& getBallCenter() const {return const_cast<RollingBallPacket*>(this)->getBallCenter();}
    virtual void setBallCenter(const Point& ballCenter);
    virtual Point& getPreviousLocation();
    virtual const Point& getPreviousLocation() const {return const_cast<RollingBallPacket*>(this)->getPreviousLocation();}
    virtual void setPreviousLocation(const Point& previousLocation);
};

inline void doPacking(cCommBuffer *b, RollingBallPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RollingBallPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _ROLLINGBALLROUTINGPACKET_M_H_

